---
name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix build --print-build-logs
      - run: nix flake check --no-build --show-trace
